### ISSUE TITLE
tracker issue: components troubleshooting and fix

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/native-mobile#96]
## Tracker issue
**Describe the bug**
Native mobile components needs to be thoroughly checked, as mobile doesnt completely works as of now. This is a tracker issue

- [x] #95 
- [x] Background from pallete error needs to be handled when background not found, NativeAppComponent.
- [ ] App crashing with Input validation(when typed, works when paste)(move to proper repo)
- [ ] After login, facing below. Immediately app crashes after showing error (move to proper repo)
![Screenshot from 2024-10-18 21-16-42](https://github.com/user-attachments/assets/814d4290-9508-4961-94c4-fa370e9f7e31)

**Comment by anantakumarghosh** [comment]
Current status:
Social signin doesnt works
App starts, checkUserExist page loads(after removing social sign in)

**Comment by anantakumarghosh** [comment]
https://github.com/wrappid/test-wrappid-app/issues/26#issuecomment-2434691723

Refer above comment. Facing issues with styles
